### PR TITLE
update malaria prevalence

### PR DESCRIPTION
**Pull request by hussain-jafari**
### Description
- *Category*: artifact
- *JIRA issue*: [MIC-4467](https://jira.ihme.washington.edu/browse/MIC-4467)
- *Research reference*: [prevalence_calculated](https://vivarium-research.readthedocs.io/en/latest/models/causes/malaria/index.html#id10)

### Changes and notes
Calculate prevalence using incidence*duration. 

### Verification and Testing
Made artifact.

### CODE REVIEW

**Comment by patricktnast** [comment]
just checking, is there an RT pull request (or somewhere otherwise documented) that we're not going to use just incidence * duration for early neonates, instead of ( incidence + duration) / 2 ?

**Comment by aflaxman** [comment]
You can find it in this table https://vivarium-research.readthedocs.io/en/latest/models/causes/malaria/index.html?highlight=malaria#id10

prevalence_calculated
For early neonatal age group: (birth_prevalence_I + (incidence_rate_c345 * duration_c345))/2. For all other age groups: incidence_rate_c345 * duration_c345

**Comment by patricktnast** [comment]
Ah, I misread this slightly--I thought that this was removing the different calculation for ENN and was just going to make everything `incidence * duration`. I forgot that `load_prevalence_from_incidence_and_duration` also does the correction for the ENN age bin.

**Review by patricktnast — APPROVED** [review]
LGTM

**Review by stevebachmeier — APPROVED** [review]

**Review by rmudambi — APPROVED** [review]

**Pull request merged**
